version: '3.8'

services:
  bot-modo-ia:
    build: .
    container_name: bot-modo-ia
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT}:5000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - awl_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  awl_network:
    external: true